site_name: Ghid Introductiv BrickBot
site_url: https://brickbot15996.github.io/brickbot-docs/

repo_url: https://github.com/BrickBot15996/brickbot-docs
repo_name: brickbot-docs

markdown_extensions:
  - pymdownx.highlight:
      use_pygments: true
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.inlinehilite
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - admonition
  - pymdownx.details
  - attr_list
  - md_in_html
  - abbr
  - pymdownx.snippets

plugins:
  - social:
      cards_layout_options:
        background_color: "#ffd100"
        color: black
        font_family: Inter
  - search

theme:
  name: material
  features:
    - navigation.tabs
    - navigation.instant
    - navigation.sections
    - navigation.instant.prefetch
    - navigation.instant.progress
    - navigation.tracking
    - navigation.path
    - navigation.indexes
    - navigation.footer
    - toc.follow
    - search.suggest
    - content.tooltips
  font:
    text: "Inter"
    code: "JetBrains Mono"
  language: ro
  favicon: logos/brickdocs_light.png
  logo: logos/brickdocs_light.png
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: light
      toggle:
        icon: material/weather-sunny
        name: Switch to dark mode
      primary: custom
      accent: custom
    - media: "(prefers-color-scheme: dark)"
      scheme: dark
      toggle:
        icon: material/weather-night
        name: Switch to light mode
      primary: custom
      accent: custom
  icon:
    admonition:
      note: fontawesome/solid/bookmark

extra:
  generator: false
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/brickbotcnu
    - icon: fontawesome/brands/instagram
      link: https://www.instagram.com/brickbotcnu
    - icon: fontawesome/solid/envelope
      link: mailto:brickbot@liceulunirea.ro
    - icon: fontawesome/solid/globe
      link: https://brickbot.ro
  analytics:
    provider: google
    property: G-W1ZNY8V2SQ

extra_css:
  - styles/stylesheet.css # Custom CSS to switch themes
  - styles/extra.css
docs_dir: "docs"
nav:
  - Acasă: index.md
  - Introducere:
      - Despre FTC: intro/about-ftc.md
      - Mentalitate de succes: intro/right-mentality.md
      - Organizarea echipei: intro/team-environment.md
  - Proiectare 3D:
      - Ce este Proiectarea 3D?: cad/cad.md
      - Onshape: cad/onshape.md
      - Printarea 3D: cad/3d-printing.md
  - Mecanică:
      - Furnizori principali: assembly/vendors.md
      - Hardware și unelte: assembly/tools-and-fasteners.md
      - Componentele mecanice: assembly/mechanical.md
      - Componentele electronice: assembly/electrical.md
      # - Mecanisme des întâlnite: assembly/mechanisms.md
      # - Cum se concepe un robot?: assembly/robot.md
      # - Cum îți faci robotul ușor de condus?: assembly/driveable-robot.md
      # - Cablare: assembly/wiring.md
  - Programare:
      - Java: programming/java.md
      - Android Studio: programming/android-studio.md
      - Java în FTC: programming/java-in-ftc.md
      # - Cum ajunge codul în robot?: programming/uploading.md
      # - Teoria controlului: programming/control-theory.md
      # - SimplicityFTC: programming/simplicityftc.md
      # - Alte resurse: programming/other-resources.md
  - Portofoliul Inginerului:
      - Introducere: portfolio/introduction.md
      - Non-Tehnic: portfolio/non-technical.md
      - Tehnic: portfolio/technical.md
  - Procesul de Jurizare:
      - Sfaturi Generale: judging/tips.md
      - Discursul: judging/presentation.md
      - Jurizarea de la stand: judging/pit.md
  - Resurse:
      - Resurse: resources/resources.md
